# Generated by Django 4.2.4 on 2023-08-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('video', models.FileField(null=True, upload_to='videos/')),
                ('str', models.FileField(null=True, upload_to='subs/')),
            ],
        ),
    ]
