# Generated by Django 4.2.4 on 2023-08-22 08:30

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_videos_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='str',
            field=models.FileField(null=True, upload_to='subs/', validators=[video.models.validate_srt_file_extension]),
        ),
    ]
