# Generated by Django 4.2.4 on 2023-08-22 08:33

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_alter_videos_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', validators=[video.models.validate_text_file_extension]),
        ),
    ]
