# Generated by Django 4.2.4 on 2023-08-22 08:27

from django.db import migrations, models
import text.models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_text_owner_alter_text_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.FileField(upload_to='text/', validators=[text.models.validate_text_file_extension]),
        ),
    ]
